language: ruby
script: "./build.sh"
branches:
  only:
  - jekyll
  except:
  - master
rvm:
- 2.4.0
env:
  global:
  - secure: dQcc00PlgrQBrOOdnKIuOao43WT2KDt4cBaTKCX40GEB13n1SEt10xeBY1w7+gyLNe4uWPeeMjLR+Qh5KI/OWBr7qMyq3xaxqgO+QYbvHJ+4nITT4KezPc6+12f0jIjwKnFIoE71zQfHamAvpCHr3CuMlXSiHxFKy3QtZlf8riNCOGxUsJf47/knX969w9ZEGybfiYH1Z5gQ95jXn003GQ4gN9t3oQEH+nj3D2yDcIS7eFT6YdGmVK1Qsn5bBMD+4kCPVBJSCespUTX7UzNFG6mdBIPwmopnbaC3n84EInHSUeJzFgEpIKS3uUzlE767qaVERes7VCaXX5HzrsToX3HapVUg1wQxaLWqMOsXtvQLQkYjTLnnBO9upJckgdCqvCQMbF9HJcZFEwCFUncPwGM1SLXdUKplBDOpy9OmxkxnYGGUdpVLhly9LF9CEXoI+iRoiwcAgj0sqozWKdUslBL16KQh7FYZ+3QDGWqoN3GPbF8Fve3J8srMeLJWwTLTrg8kohPt4+CvL9Dlz8i2P/W0eVIh/az/AU8qZsFG3A2tfvtbONzRJxlMN/r4v/1CfLlw0vLC+DdDyrfYQy2fMpczuqpX3xxpMjy2TzbtUJWL8hs3YDt3Bzad/Qltizw2+tpIOua7jdHhvbbArKTOeWSeh+8s8Mno+LNapita5oI=
